### ISSUE TITLE
automatically generate output dir

### ISSUE THREAD

**Issue by hannesbecher** [shahab-sarmashghi/RESPECT#3]
Hi Shahab,

Here's another feature request. When I specified with `-o` a directory that did not exist, `RESPECT` did not complain at the start. But after 20 mins, execution failed.

An immediate check and error message would be helpful. Even better would be if the directory was created automatically. 

Thanks and all the best, (and sorry I keep suggesting things)
Hannes

**Comment by shahab-sarmashghi** [comment]
Hi Hannes,

The output directory is automatically created now if it does not already exist.

Thank you so much for using RESPECT and providing feedback, these are very helpful, I really appreciate it.

Bests, Shahab.
