### ISSUE TITLE
Check whether output folder is empty 

### ISSUE THREAD

**Issue by hannesbecher** [shahab-sarmashghi/RESPECT#4]
Hi Shahab,

Here's another request (of low priority). If the output dir exists but is not empty, RESPECT overwrites the old output.
It would be useful if that could be avoided, for instance by adding a prefix to the latest output files.

All the best,
Hannes

**Comment by shahab-sarmashghi** [comment]
Hi Hannes,

Another good point, thanks. A counter is added to the file name if similar file names already exist.

Bests, Shahab.
