### ISSUE TITLE
with the hist file input,I got a IndexError 

### ISSUE THREAD

**Issue by helan-1997** [shahab-sarmashghi/RESPECT#7]
the code I used is as follows:
`respect -i Unknown_AL483-01R0001-01-R00_good_10w.hist -I hist-info.txt 
IndexError: single positional indexer is out-of-bounds`

**Comment by shahab-sarmashghi** [comment]
Is `hist-info.txt` formatted as described in the [documentation](https://github.com/shahab-sarmashghi/RESPECT#histogram-files)? See [example](https://github.com/shahab-sarmashghi/RESPECT/blob/main/data/hist_info.txt).

If both `.hist` and info file have the right format and you still get an error, try to run the command with `--debug` option and paste the error here please.

**Comment by helan-1997** [comment]
the hist-info is right and still get a error
the code I run:
`respect -i Unknown_AL483-01R0001-01-R00_good_10w.hist -I hist-info.txt --debug`
then I got:
`WARNING:/home/user/biodata/locust/test/Unknown_AL483-01R0001-01-R00_good_10w.hist is missing from the histogram info file; it's skipped
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/respect_env/bin/respect", line 33, in <module>
    sys.exit(load_entry_point('respect==1.3.0', 'console_scripts', 'respect')())
  File "/home/user/miniconda3/envs/respect_env/lib/python3.10/site-packages/respect/__main__.py", line 139, in main
    run_respect(args)
  File "/home/user/miniconda3/envs/respect_env/lib/python3.10/site-packages/respect/respect_functions.py", line 262, in run_respect
    pool = multiprocessing.Pool(number_of_worker_processes)
  File "/home/user/miniconda3/envs/respect_env/lib/python3.10/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/home/user/miniconda3/envs/respect_env/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1`

**Comment by helan-1997** [comment]
yes,there is a problem with the info format.then I still run this code:
`respect -i Unknown_AL483-01R0001-01-R00_good_10w.hist -I hist-info.txt`
then:
`/home/user/miniconda3/envs/respect_env/lib/python3.10/site-packages/respect-1.3.0-py3.10.egg/respect/optimizer.py:234: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._parameters_dataframe = self._parameters_dataframe.append(
/home/user/miniconda3/envs/respect_env/lib/python3.10/site-packages/respect-1.3.0-py3.10.egg/respect/optimizer.py:241: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._spectra_dataframe = self._spectra_dataframe.append(pd.Series([iteration] + list(self.repeat_spectra),`
keep circulating.

**Comment by shahab-sarmashghi** [comment]
These are warnings that you can ignore. Do you still get an error (other than these warnings)?

**Comment by helan-1997** [comment]
No problem, thank you.
